### PR TITLE
[feat] Cart

### PR DESCRIPTION
**Pull request by Ronak-Mutha**
# Cart 

image

### CODE REVIEW

**Review by rahul0396 — APPROVED** [review]
Code is decent as well as clean. Good to merge

**Review by RakshithBhat03 — APPROVED** [review]
Everything looks good. The code is clean and well structured. Good to merge

**Review by FarhanMobashir — APPROVED** [review]
everything is fine. can be merged

**Review by MaruthiPothuganti — COMMENTED** [review]
The code is clean and everything looks good to merge.

**Comment by Ronak-Mutha** [comment]
Got 2 reviews. Merging to dev branch and closing this branch.

**Pull request merged**
